# Generated by Django 4.0.6 on 2022-11-07 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('address1', models.CharField(blank=True, max_length=32, null=True)),
                ('address2', models.CharField(blank=True, max_length=32, null=True)),
                ('city', models.CharField(blank=True, max_length=32, null=True)),
                ('province', models.CharField(blank=True, max_length=32, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=8, null=True)),
                ('phone_number1', models.CharField(blank=True, max_length=32, null=True)),
                ('phone_number2', models.CharField(blank=True, max_length=32, null=True)),
                ('email', models.CharField(max_length=32)),
                ('sin', models.CharField(max_length=32)),
                ('dob', models.DateField()),
                ('agent', models.CharField(blank=True, max_length=32, null=True)),
                ('collection_amount', models.FloatField(blank=True, null=True)),
                ('collection_date', models.DateField(blank=True, null=True)),
                ('last_agent', models.CharField(blank=True, max_length=32, null=True)),
                ('last_crawl', models.DateTimeField(blank=True, null=True)),
                ('last_result', models.CharField(blank=True, max_length=32, null=True)),
                ('prioritize_local', models.BooleanField(blank=True, null=True)),
                ('prioritize_global', models.BooleanField(blank=True, null=True)),
                ('file_upload', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
