# Generated by Django 4.1.3 on 2022-11-08 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_province_alter_opportunity_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='email',
            field=models.EmailField(max_length=32),
        ),
    ]
